#!/usr/bin/env python3
"""Pack the PDX samples and timed ADPCM events used by BOS15.MDX."""
from __future__ import annotations

import argparse
from pathlib import Path

USED = (0, 1, 3, 4, 9, 15, 16, 17, 24, 63)
END_US = 134_535_011


def pdx_entry(data: bytes, index: int) -> tuple[int, int]:
    pos = index * 8
    return (int.from_bytes(data[pos : pos + 4], "big"),
            int.from_bytes(data[pos + 4 : pos + 8], "big"))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdx", type=Path, required=True)
    ap.add_argument("--events", type=Path, required=True)
    ap.add_argument("--hex", type=Path, required=True)
    ap.add_argument("--meta", type=Path, required=True)
    ap.add_argument("--event-vh", type=Path, required=True)
    args = ap.parse_args()

    pdx = args.pdx.read_bytes()
    packed = bytearray()
    sample_map: dict[int, tuple[int, int]] = {}
    for index in USED:
        source, length = pdx_entry(pdx, index)
        sample_map[index] = (len(packed), length)
        packed.extend(pdx[source : source + length])

    raw_events: list[tuple[int, str, int]] = []
    current_volume = 8
    lines = args.events.read_text().splitlines()
    parsed = [line.split() for line in lines if line.strip()]
    for n, fields in enumerate(parsed):
        time_us = int(fields[0])
        if time_us > END_US:
            break
        kind = fields[1]
        if kind == "P":
            raw_events.append((time_us, "PLAY", int(fields[2])))
            volume = int(fields[4])
            if volume != current_volume:
                current_volume = volume
                raw_events.append((time_us, "VOLUME", volume))
        elif kind == "S":
            # A play at the same timestamp resets the decoder, making stop
            # redundant and allowing all same-frame events to remain ordered.
            next_is_play = False
            for future_index in range(n + 1, len(parsed)):
                future = parsed[future_index]
                if int(future[0]) != time_us:
                    break
                if future[1] == "P":
                    next_is_play = True
                    break
            if not next_is_play:
                raw_events.append((time_us, "STOP", 0))
        elif kind == "V" and int(fields[2]) == 0:
            volume = int(fields[3])
            if volume != current_volume:
                current_volume = volume
                raw_events.append((time_us, "VOLUME", volume))

    # Convert exact microsecond timestamps to the 62.5 kHz DAC frame domain.
    events = [(round(t * 62500 / 1_000_000), kind, value)
              for t, kind, value in raw_events]

    args.hex.write_text("".join(f"{byte:02x}\n" for byte in packed))

    meta = [
        "// Generated by tools/prepare_bos_adpcm.py",
        f"localparam integer ADPCM_ROM_BYTES = {len(packed)};",
    ]
    for index in USED:
        offset, length = sample_map[index]
        meta.append(f"localparam [15:0] ADPCM_OFS_{index} = 16'd{offset};")
        meta.append(f"localparam [15:0] ADPCM_LEN_{index} = 16'd{length};")
    args.meta.write_text("\n".join(meta) + "\n")

    kind_code = {"PLAY": 0, "STOP": 1, "VOLUME": 2}
    event_lines = [
        "// Generated by tools/prepare_bos_adpcm.py",
        f"localparam integer ADPCM_EVENT_COUNT = {len(events)};",
        "function [39:0] adpcm_event;",
        "    input [9:0] index;",
        "    begin",
        "        case (index)",
    ]
    for index, (frame, kind, value) in enumerate(events):
        payload = (kind_code[kind] << 6) | value
        event_lines.append(
            f"            10'd{index}: adpcm_event = "
            f"{{32'd{frame}, 8'h{payload:02x}}}; // {kind} {value}")
    event_lines.extend([
        "            default: adpcm_event = {32'hffffffff, 8'h00};",
        "        endcase",
        "    end",
        "endfunction",
    ])
    args.event_vh.write_text("\n".join(event_lines) + "\n")
    print(f"PDX {len(pdx)} -> selected {len(packed)} bytes; {len(events)} events")


if __name__ == "__main__":
    main()
