// Generated by tools/prepare_aux_adpcm.py
localparam integer AUX_ROM_BYTES = 8448;
localparam [14:0] AUX_STARTUP_OFS = 15'd0;
localparam [15:0] AUX_STARTUP_LEN = 16'd8448;
localparam [14:0] AUX_NERUNERU_OFS = 15'd0;
localparam [15:0] AUX_NERUNERU_LEN = 16'd8448;
